parameters:
#    gwinn_tinymce_fastload.example.class: Gwinn\TinymceFastloadBundle\Example

services:
    gwinn_tinymce_fastload.file_mover:
        class: Gwinn\TinymceFastloadBundle\Util\FileMover
        calls:
            - [setFilenameGenerator, ['Gwinn\TinymceFastloadBundle\Util\FilenameSanitizer\FilenameGeneratorSanitizedTime']]